import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar-section/Navbar";
import AuthProvider from "@/lib/AuthProvider";
import { GlobalContextProvider } from "@/context/store";
import LoadingEquipment from "@/components/basic-items/LoadingEquipment";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBgCPQmyPHrOWxnUvbmQIRwOipjW8woZUreA&s",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <GlobalContextProvider>
          <body className={`${inter.className} XXdark-theme`}>
            <Navbar />
            <div>{children}</div>
            <LoadingEquipment />
            <div id="hidden-items---"></div>
          </body>
        </GlobalContextProvider>
      </AuthProvider>
    </html>
  );
}
